name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: npm
      - run: npm ci
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: -c "printenv | grep 'PRIVATE_KEY\|APP_ID\|WEBHOOK_SECRET' > .env && serverless deploy --verbose && rm .env"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
